apiVersion: v2
name: cosignwebhook
description: A Helm chart for Cosign Webhook Admission Controller
type: application
version: 5.0.0
appVersion: "5.0.0"
maintainers:
- name: eumel8
  email: f.kloeker@telekom.de
  url: https://www.telekom.com
- name: puffitos
  email: bruno.bressi@telekom.de
  url: https://www.telekom.com
